version: '3'

services:
  mongodb:
    image: mongo:latest    
    ports:
      - "27117:27017"
  lp.servicemangement:
    image: lp-servicemangement:0.0.5
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: LetPortal.ServiceManagementApis/Dockerfile
    ports:
      - "5141:80"
  lp.gateway:
    image: lp-gateway:0.0.5
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - mongodb
      - lp.servicemangement
    build:
      context: .
      dockerfile: LetPortal.Gateway/Dockerfile
    ports:
      - "5142:80"
  lp.identityapi:
    image: lp-identityapi:0.0.5
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - mongodb
      - lp.servicemangement
    build:
      context: .
      dockerfile: LetPortal.IdentityApis/Dockerfile
    ports:
      - "5143:80"
  lp.portalapi:
    image: lp-portalapi:0.0.5
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - mongodb
      - lp.servicemangement
    build:
      context: .
      dockerfile: LetPortal.WebApis/Dockerfile
    ports:
      - "5144:80"

